(part "B57164K0103J000"
    (packageRef "B57164K_K164")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "132")
    (property "Manufacturer_Name" "TDK")
    (property "Manufacturer_Part_Number" "B57164K0103J000")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Arrow_Part_Number" "B57164K0103J000")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/b57164k0103j000/epcos-tdk")
    (property "Description" "NTC thermistors for temperature measurement, lead spacing 5mm, tinned copper")
    (property "Datasheet_Link" "https://product.tdk.com/system/files/dam/doc/product/sensor/ntc/ntc_element/data_sheet/50/db/ntc/ntc_leaded_disks_k164.pdf")
    (property "symbolName1" "B57164K0103J000")
)
